#!/usr/bin/env bash

if [ $# = 0 ]
then
	nr_of_processes=4
elif [ $# = 1 ]
then
	nr_of_processes=$1
else
	echo Usage: ./start [nr_of_processes=4]
	exit 1
fi

mpicxx main.cpp Packet.cpp -o main.out -std=c++14 -lpthread

if [ $? = 0 ]
then
	
	mpiexec -n $nr_of_processes ./main.out

fi